apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  {{server-name}}
  labels:
    name:  {{server-name}}
spec:
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  {{server-name}}
    spec:
      containers:
      - image:  {{image}}
        imagePullPolicy: IfNotPresent
        name:  {{server-name}}
        resources:
          limits:
            cpu: 1000M
            memory: 1000Mi
          requests:
            memory: 2000Mi
            cpu: 2000M
        livenessProbe:
          httpGet:
            path: /
            port: {{port}}
          initialDelaySeconds: 30  # 首次启动
          timeoutSeconds: 10  # 超时
          failureThreshold: 3 #  失败次数
        readinessProbe:
          httpGet:
            path: /
            port: {{port}}
          initialDelaySeconds: 30
          timeoutSeconds: 10   
          successThreshold: 0   
        ports:
        - containerPort:  {{port}}
          name:  {{server-name}}
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name:  {{server-name}}
spec:
  selector:
    name:  {{server-name}}
  type:  ClusterIP 
  ports:
  - name: {{server-name}}
    port:  80
    targetPort:  {{port}}

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{server-name}}
spec:
  rules:
    - host: {{server-name}}-xxx.cn
      http:
        paths:
          - path: /
            backend:
              serviceName: {{server-name}}
              servicePort: 80
#  tls:
#    - hosts:
#      - {{server-name}}-xxx.cn
#      secretName:   

#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: {{server-name}}
#spec:
#  scaleTargetRef:               
#    kind: Deployment   
#    name: {{server-name}}
#  minReplicas: 1               
#  maxReplicas: 5
#  targetAverageUtilization: 50  
#
