apiVersion: apps/v1
kind: Deployment
# deployment metadata
metadata:
  name: {{ service_name }}
  labels:
    name: fuse
    app: {{ service_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ service_name }}
  template:
    metadata:
      labels:
        app: {{ service_name }}
    spec:
      imagePullSecrets:
        - name: regsecret
      containers:
      - name: {{ service_name }}
        image: {{ image }}
        resources:
          requests:
            cpu: "0.3"
            memory: 1024Mi
          limits:
            cpu: "0.6"
            memory: "2G"
        env:
          - name: ENV
            value: dev
        ports:
        - containerPort: {{ port }}
        volumeMounts:
        - name: nfs-volume            #设置的名称，和下面的name要一样的
          mountPath: /data/logs/   #需要挂载的目录
        #  subPath: newshomebg         #卷的子目录，也就是在nfs服务目录里生成这个子目录
      volumes:
      - name: nfs-volume              #这个卷的名称，和上面的name要一样的
        nfs:                          #这里是nfs挂载
          server: master         #nfs服务器的ip或者域名
          path: "/data/logs"               #nfs服务配置的挂载目录

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ service_name }}
  name: {{ service_name }}
spec:
    selector:
        app: {{ service_name }}
    ports:
        - port: {{ port }}
          name: server