---
- hosts: ft:!10.0.1.56
  user: root
  gather_facts: false
  vars:
      logstash: "10.0.1.10:5044"
      path: "/app/logs/*/*.log"
  tasks:
 # - name: 下载filebeat
 #   get_url: url=https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz  dest=files
  - name: 判断路径是否存在
    shell: ls /app/software/
    ignore_errors: True
    register: result
  - name: 创建文件夹
    file: path=/app/software/ state=directory
    when: result is failed
  - name: 安装
    unarchive: src=files/filebeat-6.5.0-linux-x86_64.tar.gz dest=/app/software/ copy=yes mode=755
  - name: 重命名
    shell: mv -f /app/software/filebeat-6.5.0-linux-x86_64 /app/software/filebeat
  - name: 配置文件
    template: src=templates/filebeat.j2 dest=/app/software/filebeat/filebeat.yml
  - name: 启动服务
    shell: "nohup /app/software/filebeat/filebeat  -c /app/software/filebeat/filebeat.yml &"
