
- name: Is user
  shell: "id {{ username }}"
  register: result
  ignore_errors: true
  tags: init-service

- name: 初始化服务器
  include: init-env.yaml
  tags: init-env


- name: 初始化服务
  include: init-service.yaml
  tags: init-service
  when: result is failed

- name: 生产NG Upstream all
  template:
    src: {{ item.src }}
    dest: {{ item.dest }}
  with_items:
    - {"src":"templates/pool.conf.j2", "dest": "/data/script/template/pool.{{ service_name }}.conf.tpl"}
    - {"src":"templates/pool.conf_01.j2", "dest": "/data/script/template/pool.{{ service_name }}.conf.close1.tpl"}
    - {"src":"templates/pool.conf_02.j2", "dest": "/data/script/template/pool.{{ service_name }}.conf.close2.tpl"}