---
  - hosts: w
    gather_facts: false
    tasks:
    #  - name: 下载java 包
    #    get_url: url='https://repo.huaweicloud.com/java/jdk/8u202-b08/jdk-8u202-linux-x64.tar.gz' dest=/tmp/ force=no
    #  - name: 判断路径是否存在
    #    shell: ls /app/software/java
    #    ignore_errors: True
    #    register: result
    #  - name: 创建文件夹
    #    file: path=/app/software/java state=directory
    #    when: result is failed
      - name: 分发压缩包
        unarchive: src=files/jdk-8u202-linux-x64.tar.gz dest=/tmp/ copy=yes mode=755
      - name: rename
        command: mv /tmp/jdk1.8.0_202 /app/software/java creates=/app/software/java
   #    when: result is failed
      - name: 环境变量
        lineinfile: 
          dest: /etc/bashrc
          line:  "{{ item }}"
          backup: yes
        with_items:
          - export  JAVA_HOME=/app/software/java
          - export  PATH=$PATH:$JAVA_HOME/bin
