apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: monitor
data:
  blackbox.yml: |-
    modules:
      http_2xx:
        prober: http
        timeout: 10s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]   
          valid_status_codes: [200]
          method: GET
          preferred_ip_protocol: "ip4"
      http_post_2xx:
        prober: http
        timeout: 10s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          method: POST
          preferred_ip_protocol: "ip4"
      tcp_connect:
        prober: tcp
        timeout: 10s
      dns:
        prober: dns
        dns:
          transport_protocol: "tcp"  # default udp
          preferred_ip_protocol: "ip4"  # default ip6
          query_name: "kubernetes.default.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: blackbox
  template:
    metadata:
      labels:
        app: blackbox
    spec:
      containers:
      - args:
        - --volume-dir=/etc/blackbox_exporter
        - --webhook-url=http://localhost:9115/-/reload
        - --webhook-method=POST
        image: jimmidyson/configmap-reload:v0.2.2
        imagePullPolicy: IfNotPresent
        name: prometheus-server-configmap-reload
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
          readOnly: true
      - image: prom/blackbox-exporter:v0.16.0
        name: blackbox
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        args:
        - --config.file=/etc/blackbox_exporter/blackbox.yml 
        - --log.level=error
        ports:
        - containerPort: 9115
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/blackbox_exporter
      volumes:
      - name: config
        configMap:
          name: blackbox-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox
  namespace: monitor
spec:
  selector:
    app: blackbox
  ports:
  - port: 9115
    targetPort: 9115