# 阿里云慢sql 入Es
mysqlurl:
  - prod-write
  - rm-report

prod-write: xx:xx@tcp(rm-xxxx.mysql.ap-southeast-5.rds.aliyuncs.com:3306)/mysql?charset=utf8&parseTime=True&loc=Local
rm-report: xx:xxx@tcp(rm-xxxxx.mysql.ap-southeast-5.rds.aliyuncs.com:3306)/mysql?charset=utf8&parseTime=True&loc=Local